services:
  redis:
    image: redis/redis-stack:latest # Redis Stack には RedisJSON などの拡張機能が含まれています
    container_name: tag_japan_redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/datadocker

  mongo:
    image: mongo:4.0
    container_name: tag_japan_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  mongo-express:
    image: mongo-express
    container_name: tag_japan_mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
  nextjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: next-app
    container_name: tag_japan_next
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./hooks:/app/hooks
      # - ./node_modules:/app/node_modules
    restart: always
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=mongodb://mongo:27017 # サービス名「mongo」をホスト名として利用
      - MONGO_DB_NAME=mydatabase # 任意のデータベース名
      - MONGO_COLLECTION=mycollection # 利用するコレクション名（必要に応じて）